baseURL = 'https://example.org/'
languageCode = 'en-gb'
title = 'Peter van der Meulen'
logo = 'logo.svg'
theme = ['photoblog']
pagination.pagerSize = 8

[menu]
[[menu.main]]
    name = "Gallery"
    pre = "image"
    url = "/galleries/"
    weight = 10
  [[menu.main]]
    name = "Posts"
    pre = "pen-tool"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    name = "About"
    pre = "id-badge"
    url = "/about/"
    weight = 30
  [[menu.contact]]
    name = "Contact"
    pre = "fa-solid fa-envelope"
    url = "/contact/"
    weight = 10
  [[menu.contact]]
    name = "Intagram"
    pre = "fa-brands fa-instagram"
    url = "https://instagram.com/"
    weight = 20
  [[menu.contact]]
    name = "Flickr"
    pre = "fa-brands fa-flickr"
    url = "https://flickr.com/"
    weight = 30
  [[menu.contact]]
    name = "GitHub"
    pre = "fa-brands fa-github"
    url = "https://github.com/"
    weight = 40